name: hs-bandit
version: 0.1.0.0
github: "bartfrenk/hs-bandit"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

default-extensions:
- OverloadedStrings
- DeriveFunctor
- RecordWildCards
- NamedFieldPuns

extra-source-files:
- README.md

synopsis: >-
  A collection of algorithms for multi-armed bandit problems.
category: Data Science

description: >-
  Please see the README on Github at
  <https://github.com/githubuser/hs-bandit#readme>

dependencies:
- base >= 4.7 && < 5
- random-fu
- random-source # only to be able to run tests in the REPL

library:
  source-dirs: src
  dependencies:
    - random-fu-multivariate
    - hmatrix
    - mtl

tests:
  hs-bandit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-bandit
