name:                hs-bandit
version:             0.1.0.0
github:              "githubuser/hs-bandit"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

default-extensions:
- OverloadedStrings
- DeriveFunctor
- RecordWildCards
- NamedFieldPuns

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hs-bandit#readme>

dependencies:
- base >= 4.7 && < 5
- free
- random-fu
- random-fu-multivariate
- hmatrix
- mtl
- exceptions
- random
- containers
- random-source # for debugging
- Chart
- Chart-diagrams

library:
  source-dirs: src

executables:
  hs-bandit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-bandit

tests:
  hs-bandit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-bandit
