name: bandit-agents
version: 0.1.0.0
github: "bartfrenk/hs-bandit"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

default-extensions:
- OverloadedStrings
- DeriveFunctor
- RecordWildCards
- NamedFieldPuns
- LambdaCase
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses


extra-source-files:
- README.md

synopsis: >-
  A collection of algorithms for multi-armed bandit problems.
category: Data Science

description: >-
  Please see the README on Github at
  <https://github.com/githubuser/hs-bandit#readme>

dependencies:
- base >= 4.7 && < 5
- random-fu
- containers
- Chart
- Chart-cairo
- random
- monad-par
- conduit
- mersenne-random-pure64

ghc-options: -Wall -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
    - random-fu-multivariate
    - hmatrix
    - hmatrix-gsl
    - mtl

executables:
  simulate:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - bandit-agents

tests:
  hs-bandit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

benchmarks:
  hs-bandit-bench:
    main: Main.hs
    source-dirs: bench
    dependencies:
      - criterion
      - bandit-agents
      - hmatrix
      - deepseq
